server:
  port: 8080

spring:
  datasource:
    username: root
    password: 8Uz1rD492
    url: jdbc:mysql://localhost:3306/crawler_bot?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# example values
indexing-settings:
  sites:
    -   url: https://www.lenta.ru
        name: Лента.ру
    -   url: https://www.skillbox.ru
        name: Skillbox
    -   url: https://www.playback.ru
        name: PlayBack.Ru
